
---
title: "IML Term project"
author: "Julia Palorinne, Pyry Silomaa, Sara Sippola"
output: pdf_document
date: '`r format(Sys.Date(), "%d.%m.%Y")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load data}
npf <- read.csv("npf_train.csv")
```

```{r preprocess data}

# Muokataan dataa.

# Luodaan class2
npf$class2 <- factor("event", levels = c("nonevent", "event"))
npf$class2[npf$class4 == "nonevent"] <- "nonevent"

# Tehdään päivämäärästä rivitunniste
rownames(npf) <- npf[, "date"]

# Poistetaan sarakkeet id, date, class4, partlybad
npf <- npf[, -(1:4)]

#Ensimmäiset perustason mallitestit
simplemod1<-glm(class4~., data=npf, family=binomial(link="logit"));simplemod1
simplemod2<-glm(class4~., data=npf, family=binomial(link="probit"));simplemod2
```

## Correlations

```{r correlations}
library(corrplot)

npfOrig <- read.csv("npf_train.csv")
npfOrig$class2[npfOrig$class4 == "nonevent"] <- 0
npfOrig$class2[npfOrig$class4 != "nonevent"] <- 1

# Select global and 16.8 m high values
npf <- data.frame(npfOrig[, (5:6)], npfOrig[, (13:16)], npfOrig[, (27:30)], 
                  npfOrig[, (41:42)], npfOrig[, (53:54)], npfOrig[, (63:72)],
                  npfOrig[, (83:88)], npfOrig[, (99:104)])

# Calculate the correlation matrix
cm <- cor(npf)

# Order variables by 1st principal component
corrplot(cm, order = "FPC", tl.cex = 0.5, tl.col = "black")
```





## Classification trees

```{r, include=TRUE}
source("classification_trees.R", local = knitr::knit_global())
```
